@startuml

scale max 4096 width
scale max 4096 height
scale 2

skinparam backgroundColor transparent
skinparam shadowing false

skinparam rectangle {
}

rectangle "Introduction to Topology" {
rectangle "Definition Topology"
rectangle "Orientable Surfaces"
rectangle "Non-orientable Surfaces"
rectangle "Homeomorphism & Genus"

"Definition Topology" -down-> "Orientable Surfaces"
"Orientable Surfaces" -down-> "Non-orientable Surfaces"
"Non-orientable Surfaces" -down-> "Homeomorphism & Genus"

}

rectangle "Planarity testing and Embedding computation" {
rectangle "Planarity condition"
rectangle "Euler's formula"
rectangle "Planarity testing"
rectangle "Planarity embedding"
rectangle "Planarity testing & embedding editor"

"Planarity condition" -down-> "Euler's formula"
"Euler's formula" -down-> "Planarity testing"
"Planarity testing" -down-> "Planarity embedding"
"Planarity embedding" -down-> "Planarity testing & embedding editor"

}

rectangle "Embeddings on other surfaces" {
rectangle "Sphere"
rectangle "Torus"
rectangle "Möbius strip"

"Sphere" -down-> "Torus"
"Torus" -down-> "Möbius strip"
}

"Definition Topology" -[hidden]right-> "Planarity condition"
"Homeomorphism & Genus" -[hidden]right-> "Planarity testing & embedding editor"
"Planarity condition" -[hidden]right-> "Sphere"
"Planarity condition" -[hidden]right-> "Sphere"
"Planarity testing & embedding editor" -[hidden]up-> "Möbius strip"

"Homeomorphism & Genus" .up.> "Planarity condition"
"Planarity testing & embedding editor" ..up..> Sphere
@enduml